services:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: insurance_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - db_mysql:/var/lib/mysql



  eureka-server:
    build: ./Back-eurika
    image: med525/eurika:1.0
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  ProjetMaghrebia:
    build: ./ProjetMaghrebia
    image: med525/med525-projet-maghrebia:1.0
    container_name: ProjetMaghrebia
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db:3306/insurance_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&max_allowed_packet=15728640
      - spring.datasource.username=root
      - spring.datasource.password=root

  API-gateway:
    build: ./apigetway
    image: med525/apigetway:1.0
    container_name: apigetway
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - ProjetMaghrebia
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

volumes:
  db_mysql:
